debug = true
interval = 100
user = "echo_kieran"

[ctfd]
api_base = "http://163.11.237.79/api/v1"
api_key = "ctfd_10698fd44950bf7556bc3f5e1012832dae5bddcffb1fe82191d8dd3be3641393"

[ntfy]
api_base = "https://ntfy.sh/"
acess_token = ""
topic = "cugencyber_ctfd"
